### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by timonegk** [ipab-slmc/eigenpy_catkin#3]
Since there have been several new releases in the upstream repository, I think that it would be appropriate to have a new release here as well.

**Comment by wxmerkt** [comment]
I agree and will work on this later this week. Are you using the catkinised eigenpy as part of MoveIt or within another project?

**Comment by timonegk** [comment]
Thank you. I am using it to build Moveit from source.

**Comment by timonegk** [comment]
Regarding the end of life of python2 in 2020, it would also be nice to make the new release python3 compatible.

**Comment by wxmerkt** [comment]
Ideally, I'd like to get the generation of native CMake config files upstream and then release as a proper third-party library to ROS. I am happy to fix MoveIt so we can move from this catkinised version to a proper third-party library release now that the upstream problems have been addressed.

Does ROS support releasing both Python2 and Python3 via the buildfarm?

**Comment by timonegk** [comment]
The release as a third-party library would of course be preferable, but I do not know how that works. As far as I know, currently the build farm only builds releases for python2, but packages for melodic should support python3 (see https://www.ros.org/reps/rep-0003.html#id3).

**Comment by wxmerkt** [comment]
As this is a compiled package (and not a "ROS Python package" as in the REP), unfortunately we cannot do this as easily.

**Comment by timonegk** [comment]
But the package should still compile for python3 when building from source with `-DPYTHON_VERSION=3`. To make that possible, the python2 paths as in https://github.com/ipab-slmc/eigenpy_catkin/blob/master/CMakeLists.txt#L22 should be replaced by variables or ifs.

**Comment by wxmerkt** [comment]
This will go away entirely as I move to a full third-party library. This hack/work-around (and the entire catkin wrapper) was previously required due to issues in the upstream buildsystem. These have now been resolved and I am in the process of re-releasing this as a regular third-party library.

**Comment by timonegk** [comment]
That is great, thank you.
Then this issue can be closed, I guess.

**Comment by wxmerkt** [comment]
Release request made: 

- Melodic: https://github.com/ros/rosdistro/pull/22797
- Kinetic: https://github.com/ros/rosdistro/pull/22798

Please note the README for required changes as well as https://github.com/ros-planning/moveit/pull/1550 for how to adapt MoveIt to be compatible with the new release.

**Comment by wxmerkt** [comment]
This repository is now deprecated as we upstreamed all required changes to release as a third-party package.
